export type LOAD_LOCATION = 'LOAD_LOCATION';
export const LOAD_LOCATION = 'LOAD_LOCATION';

export type LOAD_WEATHER = 'LOAD_WEATHER';
export const LOAD_WEATHER = 'LOAD_WEATHER';

export type SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';

export type LOAD_SETTINGS = 'LOAD_SETTINGS';
export const LOAD_SETTINGS = 'LOAD_SETTINGS';

export type TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';
export const TOGGLE_SETTINGS = 'TOGGLE_SETTINGS';

export type PRESSURE_UNIT_CHANGE = 'PRESSURE_UNIT_CHANGE';
export const PRESSURE_UNIT_CHANGE = 'PRESSURE_UNIT_CHANGE';

export type TEMP_UNIT_CHANGE = 'TEMP_UNIT_CHANGE';
export const TEMP_UNIT_CHANGE = 'TEMP_UNIT_CHANGE';

export type WIND_UNIT_CHANGE = 'WIND_UNIT_CHANGE';
export const WIND_UNIT_CHANGE = 'WIND_UNIT_CHANGE';